#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["RestfulAPI/RestfulAPI.csproj", "RestfulAPI/"]
RUN dotnet restore "RestfulAPI/RestfulAPI.csproj"
COPY . .
WORKDIR "/src/RestfulAPI"
RUN dotnet build "RestfulAPI.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "RestfulAPI.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "RestfulAPI.dll"]